### ISSUE TITLE
Fails on Maven test at Binding tests - impossible to install and use in another project

### ISSUE THREAD

**Issue by PavelSosin-320** [jcuda/jcublas#1]
Wich runtime behavior this unittest tests? I do't see that methods are added to classes via reflection, so it is attempt to chech syntax and symbol resolution via unittest. Eclipse / Maven does it better and stops build at compile phase. Test phase will be never reached. Wheather the method is native should be checked as boolean isNative = Modifier.isNative(modifiers). But it also doesn't ensure that the method is implemented in DLL

**Comment by jcuda** [comment]
In general, the `BasicBindingTest` classes only check whether each `native` method has an appropriate implementation in the DLL/SO file. It is basically a test that only checks whether calling any of the methods would otherwise cause the infamous `UnsatisfiedLinkError`. 

Providing test coverage *beyond* that ... is difficult. I can *not* sensibly test whether or not the binding of https://docs.nvidia.com/cuda/cublas/index.html#cublas-lt-t-gt-trsm does what it should do. I can only test whether the underlying CUBLAS method can be called, and *assume* that **iff** it is called, it will to the right thing. 

Some further test coverage is given via https://github.com/uncomplicate/neanderthal - but in the end, these can rather be "integration tests" instead of "unit tests".
