### ISSUE TITLE
How to set row-major mode

### ISSUE THREAD

**Issue by srmo** [jcuda/jcublas#4]
Ahoi! 

First, thanks for bringing this project to life! I'm currently following the book "The Ray-Tracer challenge" and I'm now at a stage, where I wanted to migrate my on-cpu computations to the GPU, where possible.

The implementation so far is based on row-major encoded float[] for matrices.

After migrating my multiply-matrix method based on the JCublas sample project, I find that my tests for matrix multiplication fail. 
THe values I receive in the result are just wrong. I then stumbled across your comments and the NVIDIA Cublas Docs, that they assume column-major format.

Then I found [cublasLtOrder_t](https://docs.nvidia.com/cuda/cublas/index.html#cublasltorder-t) with a possible value of `CUBLASLT_ORDER_ROW`. Now, I'm a total newb here and happy, that got this running at all with CUDA 11.
Do you intend users to set this? Where would I set this at all? Or is this an unsupported API ( cublasLt)?

My last resort would be to migrate my code-base to column-major.

**Comment by jcuda** [comment]
I think that there is no way to set "row-order" mode globally in CUBLAS itself.

The ["Data Layout" section in the documentation](https://docs.nvidia.com/cuda/cublas/index.html#data-layout) talks about the issue (and quirks and workarounds). 

> My last resort would be to migrate my code-base to column-major.

Depending on your application context, it might be relatively easy to add an abstraction layer that hides this implementation detail. For example, you could have a class like `Matrix` that could be used as `matrix.get(r,c)` and `matrix.set(r,c,,value)` without knowing whether the data internally is stored in row- or column major order. But ... when you have already spread a bunch of raw `float myMatrixInRowMajorOrder[]` arrays throughout your codebase, it could be tough...

(I could point at https://github.com/jcuda/jcuda-matrix-utils , but that's certainly not supposed to be "the" right way of doing things - you could spend _years_ with implementing "the best" Java matrix library...)

For some operations, you can exploit the fact that methods often receive a `cublasOperation_t` value. For example, you can trick the SGEMM function to work on column-major data, e.g. as described in https://stackoverflow.com/questions/56043539/cublassgemm-row-major-multiplication 

It will always be confusing. There always will be bugs caused by mixing up row- and column major. But maybe many of them can be avoided by 1. hiding the implementation detail of the order, and 2. _documenting_ which order is used, where necessary.

---

EDIT: Right, `cublasLt` is not supported in JCuda. (I could add support for that. But I'm not _that_ bored right now...). 

But `cublasLt` appears to be offered in `java-cpp`, via https://github.com/bytedeco/javacpp-presets/tree/master/cuda/src/gen/java/org/bytedeco/cuda/cublas - maybe you want to try that out.

**Comment by srmo** [comment]
Hi and thank you so much for the quick and exhaustive answer!
I'll work though the information you've provided. And yes, my whole code-base is tied to the row-major format. Then again, adding an additional abstraction layer might work, depending on the transformation overhead. 
I already have 2 different matrix implementations, one "naive", using only vanilla java float[] and another based on EJML. I can switch them in and out to test raytracer performance based on the matrix implementation. I already started with a 3rd Matrix implementation as a facade to the cublas calls so it should be easy to implement it as column major as the interface I'm using hides this from the raytracer.

Anyhow, thanks again and keep rockin!
